### PR TITLE
CRYPTO-25: Add download_crypto.cgi to exclude list of rat check

### PR DESCRIPTION
**Pull request by sundapeng**
Fixing: https://issues.apache.org/jira/browse/CRYPTO-25

@winningsix

### CODE REVIEW

**Comment by winningsix** [comment]
Thanks @sundapeng for finding this. We could add license as annotation for source file.

**Comment by sundapeng** [comment]
Thank @winningsix for your review, I think the root cause is we didn't use the same version of rat with commons. Have rebased the patch.

**Comment by winningsix** [comment]
+1

**Comment by sundapeng** [comment]
Committed to master. Thank @winningsix

**Pull request closed without merging**
