### PR TITLE
Add GitHub badges

### PR DESCRIPTION
**Pull request by britter**
Add badges for Travis CI, Maven Central and ALv2.

- The Travis Badge will become active once https://issues.apache.org/jira/browse/INFRA-12156has been resolved.
- The Maven Central badge will show the latest release version once the first release has been published.

### CODE REVIEW

**Comment by sundapeng** [comment]
Thank @britter for your contribution, I'm +1.

Nit: There is a typo at commit message `tarvis -> travis `

**Comment by britter** [comment]
@sundapeng fixed the typo. Do we want to merge this now or wait until the Travis Build has been activated by INFRA?

**Comment by sundapeng** [comment]
Thank @britter , I think both are okay. How about wait for INFRA, so that the status at github would be right.

**Comment by britter** [comment]
@sundapeng okay. Will merge when INFRA-12156 has been resolved.

**Comment by sundapeng** [comment]
Travis could work now, committed to master, thank @britter for your contribution.

**Pull request closed without merging**
