### PR TITLE
Setup site build as defined in commons-parent pom

### PR DESCRIPTION
**Pull request by britter**
Add distribution management section to pom.xml. This will allow to publish the site by calling `mvn site-deploy`. See http://commons.apache.org/site-publish.html.

### CODE REVIEW

**Comment by britter** [comment]
I've also deactivated JavaDoc lint, since the site build is failing on Java 8 otherwise.

**Comment by sundapeng** [comment]
Thank @britter for your contribution, I will fix the javadoc issues, since `DocLint` is a new feature for Java 8, how about disable `doclint` only for java 8
````
  <profile>
      <id>doclint-java8-disable</id>
      <activation>
        <jdk>[1.8,)</jdk>
      </activation>
      <properties>
        <additionalparam>-Xdoclint:none</additionalparam>
      </properties>
  </profile>

**Comment by britter** [comment]
@sundapeng thank you for the suggestion! I've moved the configuration to a profile.

**Comment by sundapeng** [comment]
+1, thank @britter

**Comment by sundapeng** [comment]
Committed to master, thank @britter for your contribution. Could you also help to close the pr?

**Comment by britter** [comment]
Thank you!

Have a look at http://wiki.apache.org/commons/UsingGIT#Applying_Pull_Requests_.28for_git_based_components.29 for information on how to mark PRs as merged via CLI.

**Comment by sundapeng** [comment]
Thank @britter for your information, it is very useful!

**Pull request closed without merging**
