### PR TITLE
CRYPTO-68: Enable common code quality reports.

### PR DESCRIPTION
**Pull request by britter**
This adds the following reports to the site build:
- findbugs (findbugs profile has been removed)
- checkstyle (checkstyle configuration copied from commons-lang)
- pmd
- taglist
- JavaNCSS

Furthermore the RAT configuration has been moved to the reporting
section of pom.xml

### CODE REVIEW

**Comment by sundapeng** [comment]
Thank @britter  for your contribution, I found the profile of findbugs have been removed at https://github.com/apache/commons-crypto/pull/48 , may I know how can we highlight the issues which are found by plugin? how about block something when the plugin found issues?

**Comment by britter** [comment]
@sundapeng I didn't know about the Jenkins job which uses the Findbugs. I can restore the profile. But I think we should add checkstyle and pmd as well and call the profile jenkins.

**Comment by sundapeng** [comment]
Thank @britter for your contribution , I can find the result on `mvn site`, I think we can improve to block `mvn site` when the plugins found issues in future.

**Comment by britter** [comment]
@sundapeng I think this has already been merged, right?

Do you want me to restore the findbugs profil for using it in CI?

**Comment by sundapeng** [comment]
Thank @britter , if we have, it would be good, but I think it isn't indispensable.

**Comment by britter** [comment]
Closing this for now. We can discuss the findbugs profile on the ML.

**Pull request closed without merging**
