### PR TITLE
[CRYPTO-152] - Bump maven-antrun-plugin from 1.8 to 3.0.0

### PR DESCRIPTION
**Pull request by arturobernalg**

### CODE REVIEW

**Comment by arturobernalg** [comment]
HI @kinow 

Any clue as to why the job don't finish?

**Comment by garydgregory** [comment]
The Crypto build is one of the more complex builds in Commons due to the need to compile C code for different OS targets: Windows, Linux, and Macos.

**Comment by arturobernalg** [comment]
mmmm sigh. And yet don't know why it's failing.  I gest travis hate me. the only log that i can see it's --> Automatic restarts limited: Please try restarting this job later or contact support@travis-ci.com.

Please any clue?

**Comment by arturobernalg** [comment]
Idem --> Please help here @sebbASF @garydgregory @sundapeng

**Pull request closed without merging**
