### PR TITLE
Introduce complete JNA implementation of cipher and cryptorandom

### PR DESCRIPTION
**Pull request by salyh**
Before merging this we should benchmark it and compare performance to JNI openssl binding

### CODE REVIEW

**Comment by sundapeng** [comment]
Thank @salyh for your great work.
I prefer the JNA implementation if performance does not decrease too much. I will do some performance test on it.

**Comment by sebbASF** [comment]
The implementation works OK for many cases, but the Cipher class crashes the JVM if
- init() is called after close()
- close() is called twice

Commenting out the call to OpensslNativeJna.EVP_CIPHER_CTX_free(context); in close() fixes the problem, but that means the context is never freed.

**Comment by salyh** [comment]
this seems to be merged somehow with https://github.com/apache/commons-crypto/commit/b6006e563f63c745c964a87fae459200ae24573b

**Comment by sundapeng** [comment]
Thank @salyh for your contribution.

**Pull request closed without merging**
