### PR TITLE
Change the value of DECRYPT_MODE to 2 to be consistent with JDK

### PR DESCRIPTION
**Pull request by dianfu**
This PR is to fix CRYPTO-29

### CODE REVIEW

**Comment by kexianda** [comment]
@dianfu , 'final ' seems better.
```java
public static final int ENCRYPT_MODE = 1;
public static final int DECRYPT_MODE = 2;
```

**Comment by dianfu** [comment]
@kexianda Thanks for the review. Make sense. Updated the PR.

**Comment by kexianda** [comment]
@dianfu 
oops, these two variable are in the interface.' public static final' seems reduntant.
Variables declared in Interface are implicitly public static final

**Comment by jerrychenhf** [comment]
+1 
@dianfu 
Please also comment in the JIRA that using the constant instead of enum is consistent with JCE.

**Comment by dianfu** [comment]
@jerrychenhf  Thanks for the review. Have commented in the JIRA about this.

**Pull request closed without merging**
